/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Categoria.Categoria;
import Jugador.Jugador;
import java.awt.Image;
import java.util.HashSet;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Miguel
 */
public class VentanaJuego extends javax.swing.JFrame {

    char vocal;
    String palabraOculta;
    public static int total_Palabras = 1;
    public static int cantidadIntentos = 0;
    public static int cantidadFallos = 0;
    public static int cantidadAciertos = 0;
    int contador = 1;
    public int i = 0; // CONTADOR DEL CICLO

    public VentanaJuego() {
        initComponents();
    }

    public static int get_cantidadIntentos() {
        return cantidadIntentos;
    }

    public static int get_total_Palabras() {
        return total_Palabras;
    }

    public static int get_cantidadFallos() {
        return cantidadFallos;
    }

    public static int get_cantidadAciertos() {
        return cantidadAciertos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textMostrar = new javax.swing.JTextField();
        BotonMostrarPalabra = new javax.swing.JButton();
        BotonA = new javax.swing.JButton();
        BotonE = new javax.swing.JButton();
        BotonI = new javax.swing.JButton();
        BotonO = new javax.swing.JButton();
        BotonU = new javax.swing.JButton();
        totalPalabras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalIntentos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalFallos = new javax.swing.JTextField();
        BotonSiguientePalabra = new javax.swing.JButton();
        botonSalir = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textMostrar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        textMostrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textMostrar.setAlignmentX(2.0F);
        textMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(textMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 83, 255, -1));

        BotonMostrarPalabra.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BotonMostrarPalabra.setText("MOSTRAR PALABRA");
        BotonMostrarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMostrarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 179, 257, -1));

        BotonA.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotonA.setText("a");
        BotonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAActionPerformed(evt);
            }
        });
        jPanel1.add(BotonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 246, 92, 66));

        BotonE.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotonE.setText("e");
        BotonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEActionPerformed(evt);
            }
        });
        jPanel1.add(BotonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 246, 92, 66));

        BotonI.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotonI.setText("i");
        BotonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIActionPerformed(evt);
            }
        });
        jPanel1.add(BotonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 246, 92, 66));

        BotonO.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotonO.setText("o");
        BotonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOActionPerformed(evt);
            }
        });
        jPanel1.add(BotonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 246, 92, 66));

        BotonU.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        BotonU.setText("u");
        BotonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUActionPerformed(evt);
            }
        });
        jPanel1.add(BotonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 246, 92, 66));

        totalPalabras.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        totalPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPalabrasActionPerformed(evt);
            }
        });
        jPanel1.add(totalPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 359, 42, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Total Palabras ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Intentos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 366, -1, -1));

        totalIntentos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        totalIntentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalIntentosActionPerformed(evt);
            }
        });
        jPanel1.add(totalIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 359, 42, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Fallos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 366, -1, -1));

        totalFallos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        totalFallos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFallosActionPerformed(evt);
            }
        });
        jPanel1.add(totalFallos, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 359, 42, -1));

        BotonSiguientePalabra.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        BotonSiguientePalabra.setText("SIGUIENTE PALABRA");
        BotonSiguientePalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguientePalabraActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSiguientePalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 425, 309, -1));

        botonSalir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonSalir.setLabel("Salir");
        botonSalir.setName("Salir"); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 0, -1, 35));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 130));

        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMostrarActionPerformed
        String palabraOculta;
        String palabraMostrar;
        char vocal;

        Categoria categoria = new Categoria();
        categoria.setArregloAnimales();

        palabraOculta = categoria.getArreglo(i);
        this.palabraOculta = categoria.getArreglo(i);
        vocal = categoria.getVocal(palabraOculta);
        this.vocal = vocal;
        palabraMostrar = categoria.quitarVocal(palabraOculta);

        textMostrar.setText(palabraMostrar);

        System.out.println("PRIMER ANIMAL : " + palabraOculta);
        System.out.println("PALABRA A MOSTRAR : " + palabraMostrar);
        System.out.println("VOCAL = " + vocal);
        textMostrar.setText(categoria.palabraMostrar);

    }//GEN-LAST:event_textMostrarActionPerformed

    private void BotonMostrarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarPalabraActionPerformed

        Icon[] vectorImagenesAnimales = new ImageIcon[10];
        Icon[] vectorImagenesColores = new ImageIcon[10];
        Icon[] vectorImagenesFrutas = new ImageIcon[10];
        vectorImagenesAnimales[0] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/oso.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesAnimales[1] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/tigre.png")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[2] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/pez.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[3] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/gato.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[4] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/raton.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[5] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/ballena.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[6] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/caracol.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[7] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/panda.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[8] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/caballo.jpg")).getImage().getScaledInstance(150, 130, 0));
        vectorImagenesAnimales[9] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosAnimales/oveja.jpg")).getImage().getScaledInstance(150, 130, 0));

        vectorImagenesColores[0] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/azul.png")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[1] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/verde.png")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[2] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/cafe.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[3] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/rojo.png")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[4] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/amarillo.png")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[5] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/morado.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[6] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/blanco.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[7] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/gris.png")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[8] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/naranja.png")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesColores[9] = new ImageIcon(new ImageIcon(getClass().getResource("/FotosColores/negro.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));

        vectorImagenesFrutas[0]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/manzana.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[1]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/fresa.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[2]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/papaya.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[3]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/mango.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[4]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/sandia.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[5]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/uvas.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[6]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/pera.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[7]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/kiwi.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[8]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/mandarina.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        vectorImagenesFrutas[9]= new ImageIcon(new ImageIcon(getClass().getResource("/FotosFrutas/limon.jpg")).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH));
        
                
        String StringTotalPalabras = Integer.toString(total_Palabras);
        totalPalabras.setText(StringTotalPalabras);
        String palabraOculta;
        String palabraMostrar;
        char vocal;
        int aux = 0;
        int contador = 0;
        //Jugador jugador = new Jugador();
        aux = Jugador.get_categoriaSeleccionada();
        System.out.println("NUMERO = " + aux);

        Categoria categoria = new Categoria();
        if (aux == 1 & contador == 0) {
            categoria.setArregloAnimales();
            contador++;
            jLabel7.setIcon(vectorImagenesAnimales[i]);
        } else if (aux == 2 & contador == 0) {
            categoria.setArregloColores();
            contador++;
            jLabel7.setIcon(vectorImagenesColores[i]);

        } else if (aux == 3 & contador == 0) {
            jLabel7.setIcon(vectorImagenesFrutas[i]);
            categoria.setArregloFrutas();
            contador++;
        }

        palabraOculta = categoria.getArreglo(i);
        this.palabraOculta = categoria.getArreglo(i);
        vocal = categoria.getVocal(palabraOculta);
        this.vocal = vocal;
        palabraMostrar = categoria.quitarVocal(palabraOculta);

        textMostrar.setText(palabraMostrar);

        System.out.println("PRIMER ANIMAL : " + palabraOculta);
        System.out.println("PALABRA A MOSTRAR : " + palabraMostrar);
        System.out.println("VOCAL = " + vocal);


    }//GEN-LAST:event_BotonMostrarPalabraActionPerformed

    private void BotonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAActionPerformed
        cantidadIntentos++;
        if ('a' == vocal) {
            textMostrar.setText(palabraOculta);

            cantidadAciertos++;

            /*String StringTotalPalabras = Integer.toString(total_Palabras);
            totalPalabras.setText(StringTotalPalabras);
            String StringTotalIntentos = Integer.toString(cantidadIntentos);
            totalIntentos.setText(StringTotalIntentos);
            String StringTotalFallos = Integer.toString(cantidadFallos);
            totalFallos.setText(StringTotalFallos);*/
        } else {

            cantidadFallos++;
            /*String StringTotalPalabras = Integer.toString(total_Palabras);
            totalPalabras.setText(StringTotalPalabras);
            String StringTotalIntentos = Integer.toString(cantidadIntentos);
            totalIntentos.setText(StringTotalIntentos);
            String StringTotalFallos = Integer.toString(cantidadFallos);
            totalFallos.setText(StringTotalFallos);*/
        }
        String StringTotalPalabras = Integer.toString(total_Palabras);
        totalPalabras.setText(StringTotalPalabras);
        String StringTotalIntentos = Integer.toString(cantidadIntentos);
        totalIntentos.setText(StringTotalIntentos);
        String StringTotalFallos = Integer.toString(cantidadFallos);
        totalFallos.setText(StringTotalFallos);

    }//GEN-LAST:event_BotonAActionPerformed

    private void totalPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPalabrasActionPerformed

    }//GEN-LAST:event_totalPalabrasActionPerformed

    private void totalIntentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalIntentosActionPerformed

    }//GEN-LAST:event_totalIntentosActionPerformed

    private void totalFallosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFallosActionPerformed

    }//GEN-LAST:event_totalFallosActionPerformed

    private void BotonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEActionPerformed
        cantidadIntentos++;
        if ('e' == vocal) {
            textMostrar.setText(palabraOculta);
            cantidadAciertos++;

        } else {
            cantidadFallos++;
        }
        String StringTotalPalabras = Integer.toString(total_Palabras);
        totalPalabras.setText(StringTotalPalabras);
        String StringTotalIntentos = Integer.toString(cantidadIntentos);
        totalIntentos.setText(StringTotalIntentos);
        String StringTotalFallos = Integer.toString(cantidadFallos);
        totalFallos.setText(StringTotalFallos);

    }//GEN-LAST:event_BotonEActionPerformed

    private void BotonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIActionPerformed
        cantidadIntentos++;
        if ('i' == vocal) {
            textMostrar.setText(palabraOculta);
            cantidadAciertos++;

        } else {
            cantidadFallos++;
        }
        String StringTotalPalabras = Integer.toString(total_Palabras);
        totalPalabras.setText(StringTotalPalabras);
        String StringTotalIntentos = Integer.toString(cantidadIntentos);
        totalIntentos.setText(StringTotalIntentos);
        String StringTotalFallos = Integer.toString(cantidadFallos);
        totalFallos.setText(StringTotalFallos);

    }//GEN-LAST:event_BotonIActionPerformed

    private void BotonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOActionPerformed
        cantidadIntentos++;
        if ('o' == vocal) {
            textMostrar.setText(palabraOculta);
            cantidadAciertos++;
        } else {
            cantidadFallos++;
        }
        String StringTotalPalabras = Integer.toString(total_Palabras);
        totalPalabras.setText(StringTotalPalabras);
        String StringTotalIntentos = Integer.toString(cantidadIntentos);
        totalIntentos.setText(StringTotalIntentos);
        String StringTotalFallos = Integer.toString(cantidadFallos);
        totalFallos.setText(StringTotalFallos);

    }//GEN-LAST:event_BotonOActionPerformed

    private void BotonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUActionPerformed
        cantidadIntentos++;
        if ('u' == vocal) {
            textMostrar.setText(palabraOculta);
            cantidadAciertos++;

        } else {
            cantidadFallos++;
        }
        String StringTotalPalabras = Integer.toString(total_Palabras);
        totalPalabras.setText(StringTotalPalabras);
        String StringTotalIntentos = Integer.toString(cantidadIntentos);
        totalIntentos.setText(StringTotalIntentos);
        String StringTotalFallos = Integer.toString(cantidadFallos);
        totalFallos.setText(StringTotalFallos);

    }//GEN-LAST:event_BotonUActionPerformed

    private void BotonSiguientePalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguientePalabraActionPerformed
        total_Palabras++;
        if (this.i == 9) { // Condicional para que no se salga del limite de 10 elementos
            this.i = 0;
        } else {
            i++;
        }

    }//GEN-LAST:event_BotonSiguientePalabraActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        VentanaEstadisticas ventanaEstadisticas = new VentanaEstadisticas();
        ventanaEstadisticas.setVisible(true);
        ventanaEstadisticas.setLocationRelativeTo(null);
        this.setVisible(false);


    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonA;
    private javax.swing.JButton BotonE;
    private javax.swing.JButton BotonI;
    private javax.swing.JButton BotonMostrarPalabra;
    private javax.swing.JButton BotonO;
    private javax.swing.JButton BotonSiguientePalabra;
    private javax.swing.JButton BotonU;
    private java.awt.Button botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textMostrar;
    private javax.swing.JTextField totalFallos;
    private javax.swing.JTextField totalIntentos;
    private javax.swing.JTextField totalPalabras;
    // End of variables declaration//GEN-END:variables
}
